# Generated by Django 5.2.17 on 2026-09-17 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingattempt',
            name='fallback_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processingattempt',
            name='fallback_observations',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
