# Generated by Django 5.2.17 on 2026-09-18 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_processingattempt_fallback_metadata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingattempt',
            name='extraction_failure_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='processingattempt',
            name='extraction_failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processingattempt',
            name='extraction_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processingattempt',
            name='extraction_result',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processingattempt',
            name='extraction_status',
            field=models.CharField(choices=[('NOT_APPLICABLE', 'Not applicable'), ('COMPLETED', 'Completed'), ('UNAVAILABLE', 'Unavailable')], default='NOT_APPLICABLE', max_length=20),
        ),
    ]
